"""Given a keypad as shown in the diagram, and an array arr[ ], your task is to list all possible words in any order which can be generated by pressing numbers from array."""

class Solution:
    # Recursive function to generate combinations
    def possibleWordsRec(self, arr, index, prefix, padMap, res):
        # Base case: if the prefix length matches arr size
        if index == len(arr):
            res.append(prefix)
            return

        # Get the corresponding digit
        digit = arr[index]

        # Skip invalid digits
        if digit < 2 or digit > 9:
            self.possibleWordsRec(arr, index + 1, prefix, padMap, res)
            return

        # Place all possible letters for this digit
        for ch in padMap[digit]:
            self.possibleWordsRec(arr, index + 1, prefix + ch, padMap, res)

    # Function to find all possible letter combinations
    def possibleWords(self, arr):
        res = []
        padMap = ["", "", "abc", "def", "ghi", "jkl", 
                "mno", "pqrs", "tuv", "wxyz"]
        self.possibleWordsRec(arr, 0, "", padMap, res)
        return res